apiVersion: v1
kind: Service

metadata:
  name: english-learning-agent-service

spec:
  selector:
    app: english-learning-agent

  ports:
  - port: 8501
    targetPort: 8501

  type: NodePort